#ifndef _StrictMorphErrors_h_
#define _StrictMorphErrors_h_

enum StrictMorphErrors
{
    STRICT_OK = 0,

    STRICT_ERROR_NOT_FOUND,
    STRICT_ERROR_INTERNAL_ERROR,
    STRICT_ERROR_ALLOCATION_ERROR,
    STRICT_ERROR_ALREADY_CREATED,
    STRICT_ERROR_NOT_CREATED,

    STRICT_ERROR_INVALID_CHARSET,
    STRICT_ERROR_INVALID_LANGUAGE,
    STRICT_ERROR_INVALID_CODEPAGE,
    STRICT_ERROR_ENUMERATION_STOPPED,
    STRICT_ERROR_INVALID_LEX_UNIT_TYPE,
    STRICT_ERROR_INVALID_LEX_UNIT_LEXID,
    STRICT_ERROR_INVALID_LEX_UNIT_DUMMY,
    STRICT_ERROR_INVALID_LEX_UNIT_FORM_NO,
    STRICT_ERROR_INVALID_LEX_UNIT_STEM_NO,
    STRICT_ERROR_INVALID_LEX_UNIT_FLEX,
    STRICT_ERROR_INVALID_LEX_UNIT_CAPS,
    STRICT_ERROR_TREE_NODE_ACCESS_FAILED,
    STRICT_ERROR_INVALID_ORTH_VARIANT,
    STRICT_ERROR_SUPPLEMENT_VARIANT_PROVIDED,
    STRICT_ERROR_ERROR_NO_SUCH_VARIANT,
    STRICT_ERROR_UNSUPPORTED_PACK_TYPE,
    STRICT_ERROR_WORD_IS_TOO_LONG,
    STRICT_ERROR_NOT_NATIVE_SYMBOL,
    STRICT_ERROR_COMPOUND_WORD_TOO_LONG,
    STRICT_ERROR_TOO_MANY_DECOMP_VARIANTS,

    STRICT_ERROR_HEADER_LOAD_FAILURE,
    STRICT_ERROR_DICT_INFO_LOAD_FAILURE,
    STRICT_ERROR_PARADIGMS_LOAD_FAILURE,
    STRICT_ERROR_PARADIGM_FORMS_LOAD_FAILURE,
    STRICT_ERROR_WORD_FORMS_LOAD_FAILURE,
    STRICT_ERROR_FLEX_DISTRIB_LOAD_FAILURE,
    STRICT_ERROR_FLEXIONS_LOAD_FAILURE,
    STRICT_ERROR_LEXEMES_LOAD_FAILURE,
    STRICT_ERROR_LEX_GDESC_LIST_LOAD_FAILURE,
    STRICT_ERROR_LEX_STEMS_LIST_LOAD_FAILURE,
    STRICT_ERROR_LEX_ORTH_LIST_LOAD_FAILURE,
    STRICT_ERROR_EXCLUDE_CHAINS_LOAD_FAILURE,
    STRICT_ERROR_EXCLUDE_INDEX_LOAD_FAILURE,
    STRICT_ERROR_STEMS_LOAD_FAILURE,

    STRICT_ERROR_HEADER_SECTION_FAILURE,
    STRICT_ERROR_DICT_INFO_SECTION_FAILURE,
    STRICT_ERROR_PARADIGMS_SECTION_FAILURE,
    STRICT_ERROR_PARADIGM_FORMS_SECTION_FAILURE,
    STRICT_ERROR_WORD_FORMS_SECTION_FAILURE,
    STRICT_ERROR_FLEX_DISTRIB_SECTION_FAILURE,
    STRICT_ERROR_FLEXIONS_SECTION_FAILURE,
    STRICT_ERROR_LEXEMES_SECTION_FAILURE,
    STRICT_ERROR_LEX_GDESC_LIST_SECTION_FAILURE,
    STRICT_ERROR_LEX_STEMS_LIST_SECTION_FAILURE,
    STRICT_ERROR_LEX_ORTH_LIST_SECTION_FAILURE,
    STRICT_ERROR_EXCLUDE_CHAINS_SECTION_FAILURE,
    STRICT_ERROR_EXCLUDE_INDEX_SECTION_FAILURE,
    STRICT_ERROR_STEMS_SECTION_FAILURE,

    STRICT_ERROR_HEADER_SAVE_FAILURE,
    STRICT_ERROR_DICT_INFO_SAVE_FAILURE,
    STRICT_ERROR_PARADIGMS_SAVE_FAILURE,
    STRICT_ERROR_PARADIGM_FORMS_SAVE_FAILURE,
    STRICT_ERROR_WORD_FORMS_SAVE_FAILURE,
    STRICT_ERROR_FLEX_DISTRIB_SAVE_FAILURE,
    STRICT_ERROR_FLEXIONS_SAVE_FAILURE,
    STRICT_ERROR_LEXEMES_SAVE_FAILURE,
    STRICT_ERROR_LEX_GDESC_LIST_SAVE_FAILURE,
    STRICT_ERROR_LEX_STEMS_LIST_SAVE_FAILURE,
    STRICT_ERROR_LEX_ORTH_LIST_SAVE_FAILURE,
    STRICT_ERROR_EXCLUDE_CHAINS_SAVE_FAILURE,
    STRICT_ERROR_EXCLUDE_INDEX_SAVE_FAILURE,
    STRICT_ERROR_STEMS_SAVE_FAILURE,
    
    STRICT_ERROR_ENUMERATION_FUNCTOR,

    STRICT_ERROR_OPEN_FILE,
    
    STRICT_ERROR_NONE
};

#endif /* _StrictMorphErrors_h_ */
